### ISSUE TITLE
Update required for version 2.1.0 - nightly

### ISSUE THREAD

**Issue by Abhijit-2592** [rbhambriiit/home#1]
The code you gave to convert spacy data to Json for training with CLI requires a slight tweaking to work with the upcoming spacy 2.1.0 release.

In this [line](https://github.com/rbhambriiit/home/blob/master/spacy_enhanced/train_data_to_json.py#L96)

should be converted to:
`nlp = spacy.load('en', disable = ["ner"])`

Because, the fix to [this](https://github.com/explosion/spaCy/issues/2550) issue raises an error when you are trying to set a different entity to a already present entity

**Comment by rbhambriiit** [comment]
Sure, makes sense. I see you have fixed it.
Closing this bug.
